### ISSUE TITLE
Build currently fails

### ISSUE THREAD

**Issue by drseb** [phenopackets/phenopacket-schema#41]
I just cloned the repo and started a `./mvnw clean install`, which leads to two errors:

1)
```[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ phenopacket-schema ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 24 source files to /Users/koehlers/git/phenopacket-schema/target/test-classes
[ERROR] error reading /Users/koehlers/.m2/repository/org/apache/commons/commons-lang3/3.6/commons-lang3-3.6.jar; invalid LOC header (bad signature)
```

The other one is in Tests:
```
[INFO] Running org.phenopackets.schema.v1.FhirTest
[ERROR] Tests run: 2, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.055 s <<< FAILURE! - in org.phenopackets.schema.v1.FhirTest
[ERROR] org.phenopackets.schema.v1.FhirTest.testCancerExample()  Time elapsed: 0.051 s  <<< FAILURE!
java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils
	at org.hl7.fhir.r4.model.IdType.setValue(IdType.java:420)
	at org.hl7.fhir.r4.model.Resource.setId(Resource.java:133)
	at org.phenopackets.schema.v1.examples.CancerFhirExample.cancerBundle(CancerFhirExample.java:25)
	at org.phenopackets.schema.v1.examples.TestExamples.cancerBundle(TestExamples.java:42)
	at org.phenopackets.schema.v1.FhirTest.testCancerExample(FhirTest.java:19)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.StringUtils
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more

[ERROR] org.phenopackets.schema.v1.FhirTest.testRareDiseaseExample()  Time elapsed: 0.001 s  <<< FAILURE!
java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils
	at org.hl7.fhir.r4.model.IdType.setValue(IdType.java:420)
	at org.hl7.fhir.r4.model.Resource.setId(Resource.java:133)
	at org.phenopackets.schema.v1.examples.RareDiseaseFhirExample.rareDiseaseBundle(RareDiseaseFhirExample.java:24)
	at org.phenopackets.schema.v1.examples.TestExamples.rareDiseaseBundle(TestExamples.java:28)
	at org.phenopackets.schema.v1.FhirTest.testRareDiseaseExample(FhirTest.java:25)
```

**Comment by julesjacobsen** [comment]
Odd. Works for me and the CI server.
Are you using Java 8+? Try deleting Users/koehlers/.m2/repository/org/apache/commons/commons-lang3/3.6/commons-lang3-3.6.jar it might be corrupted.

**Comment by drseb** [comment]
yes. that did the trick. thanks
